name: Deploy website to S3
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      AWS_DEFAULT_REGION: '{{ secrets.S3_BUCKET_REGION }}'
    steps:
      - uses: actions/checkout@v2
      - name: Upload to S3
        run: aws s3 sync ./build s3://${{ secrets.S3_BUCKET}}
